apiVersion: apps/v1 # Usa apps/v1beta2 para versiones anteriores a 1.9.0
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  selector:
    matchLabels:
      app: backend
  replicas: 2 # indica al controlador que ejecute 2 pods
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: marquitosdocker/backend
        ports:
        - containerPort: 8080
        env:
          # Use secret in real usage
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-configmap
              key: host
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: db-configmap
              key: name
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: db-root-credentials
              key: USER_NAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-root-credentials
              key: PASSWORD      
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
   app: backend
spec:
  selector:
    app: backend
  ports:
    - nodePort: 30007
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort      